export type EditorialState = "pilot" | "guide" | "reference";

export type CurriculumLesson = {
  id: string;
  summary: string;
  prerequisites: string[];
  editorialState: EditorialState;
};

export type CurriculumDetails = {
  contentVersion: number;
  contentReadiness: "ready" | "partial" | "summary" | "reference";
  estimatedMinutes: number;
  outcomes: string[];
  traceIds: string[];
  exerciseIds: string[];
};

export type CurriculumStage = {
  id: string;
  title: string;
  description: string;
  slugs: string[];
};

export const curriculumStages: CurriculumStage[] = [
  {
    id: "foundations",
    title: "Foundations",
    description: "Count work, name growth, and see what Python collections actually cost.",
    slugs: ["input-size-and-operation-counts", "asymptotic-growth", "cost-models", "loop-invariants", "arrays-and-python-costs", "dynamic-array-growth", "recursion-and-recurrences"],
  },
  {
    id: "linear-structures",
    title: "Linear structures",
    description: "Follow links, stacks, and queues, and keep both neighbors when a node can move.",
    slugs: ["singly-linked-list", "fast-slow-pointer-patterns", "linked-list-reversal-and-relinking", "linked-list-merge-and-sort", "linked-list-special-cases", "doubly-linked-list-operations", "stack-basics", "monotonic-stack-patterns", "stack-parsing-and-expressions", "queue-and-deque-operations"],
  },
  {
    id: "search-and-ordering",
    title: "Search and ordering",
    description: "Sort, then use that order to search and to pick one rank.",
    slugs: ["comparison-sorts", "merge-sort", "quicksort-and-partition", "binary-search", "binary-search-on-answer", "noncomparison-sorts", "order-statistic-selection", "inversion-counting"],
  },
  {
    id: "lookup-and-priority",
    title: "Lookup and priority",
    description: "Look up keys, keep a search tree ordered, and pick the next item by priority.",
    slugs: ["hash-chaining", "hash-linear-probing", "lru-cache", "binary-search-tree-operations", "tree-traversals", "balanced-search-trees", "heap-operations", "priority-queues"],
  },
  {
    id: "graphs",
    title: "Graphs",
    description: "Model connections, walk them, and build a spanning tree without cycles.",
    slugs: ["graph-representations", "graph-traversals", "topological-order", "shortest-paths", "union-find", "minimum-spanning-trees"],
  },
  {
    id: "problem-solving",
    title: "Problem-solving methods",
    description: "Recognize a pattern, then account for its cost.",
    slugs: ["two-pointers", "sliding-window", "prefix-sums", "backtracking", "greedy-methods", "dynamic-programming", "dp-state-and-transition"],
  },
  {
    id: "advanced-applications",
    title: "Advanced applications",
    description: "Apply the same ideas to text, ranges, storage, and approximation.",
    slugs: ["string-search", "tries-and-text-indexes", "range-query-structures", "approximate-membership", "storage-engines-and-locality", "approximation-guarantees"],
  },
  {
    id: "reference",
    title: "Python reference",
    description: "Module maps and small language examples. These pages are not part of the numbered sequence.",
    slugs: ["analysis-and-library-costs", "list-algorithms", "stacks", "queues-and-deque", "sorting", "sorting-extras", "heaps", "hash-table", "binary-search-tree", "doubly-linked-list-and-lru-cache", "graphs", "greedy-algorithms", "backtracking-and-array-patterns", "strings", "range-queries-and-approximate-structures", "storage-and-locality", "limits-and-approximation", "appendix-python-tools"],
  },
];

export const curriculumLessons: Record<string, CurriculumLesson> = {
  "analysis-and-library-costs": {
    id: "lesson-analysis-and-library-costs",
    summary: "Estimate the work and memory an algorithm uses, including the cost of common Python operations.",
    prerequisites: [],
    editorialState: "reference",
  },
  "input-size-and-operation-counts": {
    id: "lesson-input-size-and-operation-counts",
    summary: "Choose an input-size variable and translate simple loops into operation counts.",
    prerequisites: [],
    editorialState: "guide",
  },
  "asymptotic-growth": {
    id: "lesson-asymptotic-growth",
    summary: "Use upper, tight and lower bounds to compare how algorithm work grows.",
    prerequisites: ["input-size-and-operation-counts"],
    editorialState: "guide",
  },
  "cost-models": {
    id: "lesson-cost-models",
    summary: "State the assumptions behind complexity claims and account for real Python operations.",
    prerequisites: ["asymptotic-growth"],
    editorialState: "guide",
  },
  "loop-invariants": {
    id: "lesson-loop-invariants",
    summary: "Check initialization, preservation and termination to reason about a loop's correctness.",
    prerequisites: ["input-size-and-operation-counts"],
    editorialState: "guide",
  },
  "arrays-and-python-costs": {
    id: "lesson-arrays-and-python-costs",
    summary: "Choose list or deque operations based on indexing, endpoints, movement and amortized cost.",
    prerequisites: ["cost-models"],
    editorialState: "guide",
  },
  "recursion-and-recurrences": {
    id: "lesson-recursion-and-recurrences",
    summary: "Translate recursive calls into recurrences and count levels, work and stack space.",
    prerequisites: ["asymptotic-growth"],
    editorialState: "guide",
  },
  "dynamic-array-growth": {
    id: "lesson-dynamic-array-growth",
    summary: "Relate geometric capacity growth to total copy work and amortized append cost.",
    prerequisites: ["arrays-and-python-costs"],
    editorialState: "guide",
  },
  "singly-linked-list": {
    id: "lesson-singly-linked-list",
    summary: "Trace how nodes and a cached tail support list operations with different costs.",
    prerequisites: ["arrays-and-python-costs"],
    editorialState: "guide",
  },
  "list-algorithms": {
    id: "lesson-list-algorithms",
    summary: "Use pointer patterns to reverse, rotate, merge, and inspect linked lists.",
    prerequisites: ["singly-linked-list"],
    editorialState: "reference",
  },
  "stack-basics": {
    id: "lesson-stack-basics",
    summary: "Trace last-in, first-out operations and maintain a bounded stack's size invariant.",
    prerequisites: ["arrays-and-python-costs"],
    editorialState: "guide",
  },
  "monotonic-stack-patterns": {
    id: "lesson-monotonic-stack-patterns",
    summary: "Use a monotonic stack to resolve next-greater and related candidates in linear total work.",
    prerequisites: ["stack-basics"],
    editorialState: "guide",
  },
  "stack-parsing-and-expressions": {
    id: "lesson-stack-parsing-and-expressions",
    summary: "Apply stack order to nested delimiters, operator precedence and auxiliary stack patterns.",
    prerequisites: ["stack-basics"],
    editorialState: "guide",
  },
  "fast-slow-pointer-patterns": {
    id: "lesson-fast-slow-pointer-patterns",
    summary: "Use pointer speed and a fixed gap to find middles, detect cycles, and locate nodes from the end.",
    prerequisites: ["singly-linked-list"],
    editorialState: "guide",
  },
  "linked-list-reversal-and-relinking": {
    id: "lesson-linked-list-reversal-and-relinking",
    summary: "Preserve every node while reversing or rearranging links in a chain.",
    prerequisites: ["singly-linked-list"],
    editorialState: "guide",
  },
  "linked-list-merge-and-sort": {
    id: "lesson-linked-list-merge-and-sort",
    summary: "Combine ordered linked lists and use bottom-up merging to sort without random access.",
    prerequisites: ["singly-linked-list"],
    editorialState: "guide",
  },
  "linked-list-special-cases": {
    id: "lesson-linked-list-special-cases",
    summary: "Read the preconditions behind duplicate removal, node deletion, digit lists, and circular splits.",
    prerequisites: ["singly-linked-list"],
    editorialState: "guide",
  },
  "doubly-linked-list-and-lru-cache": {
    id: "lesson-doubly-linked-list-and-lru-cache",
    summary: "Connect two-way links with key lookup to build an LRU cache.",
    prerequisites: ["doubly-linked-list-operations", "lru-cache"],
    editorialState: "reference",
  },
  "doubly-linked-list-operations": {
    id: "lesson-doubly-linked-list-operations",
    summary: "Maintain both neighbor links during insertion, removal, and movement of known nodes.",
    prerequisites: ["singly-linked-list"],
    editorialState: "guide",
  },
  "lru-cache": {
    id: "lesson-lru-cache",
    summary: "Combine constant-expected-time key lookup with recency ordering and eviction.",
    prerequisites: ["hash-chaining", "doubly-linked-list-operations"],
    editorialState: "guide",
  },
  stacks: {
    id: "lesson-stacks",
    summary: "Use last-in, first-out behavior for parsing, monotonic scans, and stack-based algorithms.",
    prerequisites: ["stack-basics"],
    editorialState: "reference",
  },
  sorting: {
    id: "lesson-sorting",
    summary: "Compare simple and efficient sorting algorithms by work, memory, stability, and input order.",
    prerequisites: ["comparison-sorts"],
    editorialState: "reference",
  },
  "comparison-sorts": {
    id: "lesson-comparison-sorts",
    summary: "Compare simple sorting invariants, input sensitivity and stability.",
    prerequisites: ["arrays-and-python-costs", "recursion-and-recurrences"],
    editorialState: "guide",
  },
  "merge-sort": {
    id: "lesson-merge-sort",
    summary: "Derive merge sort's work from its levels and account for merge storage.",
    prerequisites: ["comparison-sorts", "recursion-and-recurrences"],
    editorialState: "guide",
  },
  "quicksort-and-partition": {
    id: "lesson-quicksort-and-partition",
    summary: "Use a partition invariant and relate pivot balance to quicksort's cost.",
    prerequisites: ["comparison-sorts"],
    editorialState: "guide",
  },
  "binary-search": {
    id: "lesson-binary-search",
    summary: "Trace why a sorted sequence lets each comparison rule out half the remaining indexes.",
    prerequisites: ["comparison-sorts"],
    editorialState: "pilot",
  },
  "binary-search-on-answer": {
    id: "lesson-binary-search-on-answer",
    summary: "Search a monotonic feasibility decision and account for each check's cost.",
    prerequisites: ["binary-search"],
    editorialState: "guide",
  },
  "queues-and-deque": {
    id: "lesson-queues-and-deque",
    summary: "Compare FIFO queues, ring buffers, dynamic arrays, and deques by where operations happen.",
    prerequisites: ["queue-and-deque-operations"],
    editorialState: "reference",
  },
  "queue-and-deque-operations": {
    id: "lesson-queue-and-deque-operations",
    summary: "Compare FIFO and double-ended operations with linked and circular-buffer invariants.",
    prerequisites: ["arrays-and-python-costs", "singly-linked-list"],
    editorialState: "guide",
  },
  heaps: {
    id: "lesson-heaps",
    summary: "Maintain a partial order when the next smallest or largest item matters most.",
    prerequisites: ["heap-operations"],
    editorialState: "reference",
  },
  "hash-table": {
    id: "lesson-hash-table",
    summary: "Use hashes for expected fast lookup and see what collisions do to that expectation.",
    prerequisites: ["hash-chaining"],
    editorialState: "reference",
  },
  "binary-search-tree": {
    id: "lesson-binary-search-tree",
    summary: "Walk ordered keys through ordinary and balanced search trees, and relate height to cost.",
    prerequisites: ["binary-search-tree-operations"],
    editorialState: "reference",
  },
  "hash-chaining": {
    id: "lesson-hash-chaining",
    summary: "Trace collision buckets and understand how load factor relates to expected chain length.",
    prerequisites: ["arrays-and-python-costs"],
    editorialState: "guide",
  },
  "hash-linear-probing": {
    id: "lesson-hash-linear-probing",
    summary: "Trace open-addressing probes, tombstones, and clustering in a table array.",
    prerequisites: ["hash-chaining"],
    editorialState: "guide",
  },
  "binary-search-tree-operations": {
    id: "lesson-binary-search-tree-operations",
    summary: "Trace ordered lookup, insertion, deletion, and successor operations in a BST.",
    prerequisites: ["binary-search"],
    editorialState: "guide",
  },
  "tree-traversals": {
    id: "lesson-tree-traversals",
    summary: "Compare depth-first and level-order traversals and predict their visit orders.",
    prerequisites: ["binary-search-tree-operations", "queue-and-deque-operations"],
    editorialState: "guide",
  },
  "balanced-search-trees": {
    id: "lesson-balanced-search-trees",
    summary: "Explain how balancing keeps search-tree height logarithmic through rotations.",
    prerequisites: ["binary-search-tree-operations"],
    editorialState: "guide",
  },
  "heap-operations": {
    id: "lesson-heap-operations",
    summary: "Trace heap insertion, removal, heap construction, and heapsort using array indexes.",
    prerequisites: ["arrays-and-python-costs"],
    editorialState: "guide",
  },
  "priority-queues": {
    id: "lesson-priority-queues",
    summary: "Choose a priority-queue operation and explain the heap cost behind it.",
    prerequisites: ["heap-operations"],
    editorialState: "guide",
  },
  "union-find": {
    id: "lesson-union-find",
    summary: "Track which items are connected as sets merge, with and without balancing heuristics.",
    prerequisites: ["graph-representations"],
    editorialState: "guide",
  },
  "graph-representations": { id: "lesson-graph-representations", summary: "Choose adjacency lists or matrices based on graph density and required operations.", prerequisites: ["arrays-and-python-costs"], editorialState: "guide" },
  "graph-traversals": { id: "lesson-graph-traversals", summary: "Trace depth-first and breadth-first search and account for visited state.", prerequisites: ["graph-representations", "queue-and-deque-operations"], editorialState: "guide" },
  "topological-order": { id: "lesson-topological-order", summary: "Order dependency graphs and detect cycles using indegrees.", prerequisites: ["graph-traversals"], editorialState: "guide" },
  "shortest-paths": { id: "lesson-shortest-paths", summary: "Choose BFS or Dijkstra from edge weights and trace relaxation correctly.", prerequisites: ["graph-traversals", "heap-operations"], editorialState: "guide" },
  "minimum-spanning-trees": { id: "lesson-minimum-spanning-trees", summary: "Trace Kruskal's algorithm and use union-find to avoid cycles.", prerequisites: ["union-find", "graph-representations"], editorialState: "guide" },
  "sorting-extras": {
    id: "lesson-sorting-extras",
    summary: "Extend comparison sorting with radix methods and order-statistic selection.",
    prerequisites: ["noncomparison-sorts", "order-statistic-selection"],
    editorialState: "reference",
  },
  "noncomparison-sorts": {
    id: "lesson-noncomparison-sorts",
    summary: "Use bounded ranges and digit passes when key structure permits non-comparison sorting.",
    prerequisites: ["comparison-sorts"],
    editorialState: "guide",
  },
  "order-statistic-selection": {
    id: "lesson-order-statistic-selection",
    summary: "Find one sorted rank with quickselect without ordering every item.",
    prerequisites: ["quicksort-and-partition"],
    editorialState: "guide",
  },
  "inversion-counting": {
    id: "lesson-inversion-counting",
    summary: "Count out-of-order pairs while merging sorted runs.",
    prerequisites: ["merge-sort"],
    editorialState: "guide",
  },
  graphs: {
    id: "lesson-graphs",
    summary: "Represent relationships and trace traversals, shortest paths, and spanning-tree algorithms.",
    prerequisites: ["graph-representations"],
    editorialState: "reference",
  },
  "dynamic-programming": {
    id: "lesson-dynamic-programming",
    summary: "Turn repeated subproblems into bottom-up tables and analyze time and memory separately.",
    prerequisites: ["recursion-and-recurrences"],
    editorialState: "guide",
  },
  "greedy-algorithms": {
    id: "lesson-greedy-algorithms",
    summary: "Choose locally useful steps and examine when that choice leads to a global optimum.",
    prerequisites: ["greedy-methods"],
    editorialState: "reference",
  },
  "backtracking-and-array-patterns": {
    id: "lesson-backtracking-and-array-patterns",
    summary: "Search a space of choices and recognize two-pointer, window, prefix-sum, and deque patterns.",
    prerequisites: ["two-pointers", "backtracking"],
    editorialState: "reference",
  },
  "two-pointers": { id: "lesson-two-pointers", summary: "Use a movement invariant to justify scans from ends, gaps, or paired inputs.", prerequisites: ["arrays-and-python-costs"], editorialState: "guide" },
  "sliding-window": { id: "lesson-sliding-window", summary: "Maintain a contiguous range as it grows and shrinks under a valid monotone condition.", prerequisites: ["two-pointers"], editorialState: "guide" },
  "prefix-sums": { id: "lesson-prefix-sums", summary: "Answer range-sum queries and count target-sum subarrays from cumulative totals.", prerequisites: ["arrays-and-python-costs"], editorialState: "guide" },
  "backtracking": { id: "lesson-backtracking", summary: "Explore choice trees with reversible state, safe pruning and explicit search costs.", prerequisites: ["recursion-and-recurrences"], editorialState: "guide" },
  "greedy-methods": { id: "lesson-greedy-methods", summary: "Evaluate a locally best choice and justify it with a structural proof.", prerequisites: ["comparison-sorts"], editorialState: "guide" },
  "dp-state-and-transition": { id: "lesson-dp-state-and-transition", summary: "Define dynamic-programming states, transitions, base cases, fill order and cost.", prerequisites: ["dynamic-programming"], editorialState: "guide" },
  strings: {
    id: "lesson-strings",
    summary: "Search, index, and compress text with tries, pattern matching, hashes, and suffix arrays.",
    prerequisites: ["string-search"],
    editorialState: "reference",
  },
  "string-search": { id: "lesson-string-search", summary: "Trace KMP fallback and rolling-hash candidate verification for pattern matching.", prerequisites: ["arrays-and-python-costs"], editorialState: "guide" },
  "tries-and-text-indexes": { id: "lesson-tries-and-text-indexes", summary: "Compare prefix tries and text indexes by query, build cost and storage.", prerequisites: ["string-search"], editorialState: "guide" },
  "range-query-structures": { id: "lesson-range-query-structures", summary: "Choose Fenwick trees, segment trees or sparse tables from update and query needs.", prerequisites: ["cost-models"], editorialState: "guide" },
  "approximate-membership": { id: "lesson-approximate-membership", summary: "Explain Bloom-filter guarantees, false positives and workload assumptions.", prerequisites: ["hash-chaining"], editorialState: "guide" },
  "storage-engines-and-locality": { id: "lesson-storage-engines-and-locality", summary: "Compare B-tree and LSM costs across reads, writes and locality.", prerequisites: ["balanced-search-trees", "range-query-structures"], editorialState: "guide" },
  "approximation-guarantees": { id: "lesson-approximation-guarantees", summary: "Prove feasibility and a factor-two bound for a vertex-cover construction.", prerequisites: ["greedy-methods"], editorialState: "guide" },
  "range-queries-and-approximate-structures": {
    id: "lesson-range-queries-and-approximate-structures",
    summary: "Answer exact range questions and understand the tradeoffs of probabilistic structures.",
    prerequisites: ["range-query-structures"],
    editorialState: "reference",
  },
  "storage-and-locality": {
    id: "lesson-storage-and-locality",
    summary: "Connect in-memory trees, write-ahead logs, sorted runs, and locality to storage-engine behavior.",
    prerequisites: ["storage-engines-and-locality"],
    editorialState: "reference",
  },
  "limits-and-approximation": {
    id: "lesson-limits-and-approximation",
    summary: "Separate what can be solved exactly from what needs an approximation or an assumption.",
    prerequisites: ["approximation-guarantees"],
    editorialState: "reference",
  },
  "appendix-python-tools": {
    id: "reference-python-tools",
    summary: "Look up small Python decorator and directory-walking examples when needed.",
    prerequisites: [],
    editorialState: "reference",
  },
};

export const curriculumDetails: Record<string, CurriculumDetails> = {
  "analysis-and-library-costs": { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 18, outcomes: ["Estimate loop and recursion work", "Compare common Python collection operations"], traceIds: [], exerciseIds: [] },
  "input-size-and-operation-counts": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 12, outcomes: ["Choose an input-size variable", "Count work in simple and nested loops"], traceIds: ["input-size-and-operation-counts-core"], exerciseIds: ["input-size-and-operation-counts-check"] },
  "asymptotic-growth": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 12, outcomes: ["Distinguish O, Θ and Ω", "Compare common growth rates"], traceIds: ["asymptotic-growth-core"], exerciseIds: ["asymptotic-growth-check"] },
  "cost-models": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["State assumptions behind a complexity claim", "Separate algorithm steps from Python container costs"], traceIds: [], exerciseIds: [] },
  "loop-invariants": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 12, outcomes: ["State a loop invariant", "Check initialization, preservation and termination"], traceIds: ["loop-invariants-core"], exerciseIds: ["loop-invariants-check"] },
  "arrays-and-python-costs": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 14, outcomes: ["Choose list or deque from the operation pattern", "Distinguish amortized append from front insertion"], traceIds: ["arrays-and-python-costs-core"], exerciseIds: ["arrays-and-python-costs-check"] },
  "recursion-and-recurrences": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 14, outcomes: ["Recognize common recurrence shapes", "Count recursive levels and stack memory"], traceIds: ["recursion-and-recurrences-core"], exerciseIds: ["recursion-and-recurrences-check"] },
  "dynamic-array-growth": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 12, outcomes: ["Explain geometric capacity growth", "Distinguish amortized append from one resize"], traceIds: ["dynamic-array-growth-core"], exerciseIds: ["dynamic-array-growth-check"] },
  "singly-linked-list": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 20, outcomes: ["Trace node links and list invariants", "Compare append, search and indexed access costs"], traceIds: ["singly-linked-list-core"], exerciseIds: ["singly-linked-list-check"] },
  "list-algorithms": { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 30, outcomes: ["Use slow/fast and split/merge pointer patterns", "Explain how each pointer update preserves list structure"], traceIds: [], exerciseIds: [] },
  "fast-slow-pointer-patterns": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Explain fast/slow pointer middle and cycle behavior", "Use a fixed gap to locate a node from the end"], traceIds: [], exerciseIds: [] },
  "linked-list-reversal-and-relinking": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Maintain reversed prefix and untouched suffix", "Identify reconnection boundaries for relinking operations"], traceIds: [], exerciseIds: [] },
  "linked-list-merge-and-sort": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Merge sorted chains by comparing their heads", "Derive bottom-up merge-sort time and auxiliary space"], traceIds: [], exerciseIds: [] },
  "linked-list-special-cases": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 12, outcomes: ["State specialized linked-list preconditions", "Choose boundary tests for unusual input shapes"], traceIds: [], exerciseIds: [] },
  "stack-basics": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 12, outcomes: ["Trace LIFO order", "State bounded stack size invariants"], traceIds: ["stack-basics-core"], exerciseIds: ["stack-basics-check"] },
  "monotonic-stack-patterns": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Trace unresolved candidates and pops", "Derive linear total work from one push/pop per item"], traceIds: [], exerciseIds: [] },
  "stack-parsing-and-expressions": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Use a stack to match nested delimiters", "Trace operator precedence using an operator stack"], traceIds: [], exerciseIds: [] },
  "queue-and-deque-operations": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 14, outcomes: ["Trace FIFO order", "Compare linked and circular queue invariants"], traceIds: ["queue-and-deque-operations-core"], exerciseIds: ["queue-and-deque-operations-check"] },
  "doubly-linked-list-and-lru-cache": { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 24, outcomes: ["Maintain next and previous links during edits", "Combine key lookup and recency order in an LRU cache"], traceIds: [], exerciseIds: [] },
  "doubly-linked-list-operations": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 12, outcomes: ["Update both neighbors when inserting or removing a node", "Explain why a known-node unlink is constant time"], traceIds: [], exerciseIds: [] },
  "lru-cache": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Trace promotion and least-recent eviction", "Relate dictionary and list operations to cache complexity"], traceIds: [], exerciseIds: [] },
  stacks: { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 25, outcomes: ["Apply last-in, first-out behavior", "Recognize stacks in parsing and monotonic scans"], traceIds: [], exerciseIds: [] },
  sorting: { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 30, outcomes: ["Compare sorting work and memory", "Choose a sort based on stability and input characteristics"], traceIds: [], exerciseIds: [] },
  "comparison-sorts": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 14, outcomes: ["Compare simple sorting invariants", "Relate input order to best-case work and stability"], traceIds: ["comparison-sorts-core"], exerciseIds: ["comparison-sorts-check"] },
  "merge-sort": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 14, outcomes: ["Trace a stable merge", "Derive time and auxiliary-space costs"], traceIds: ["merge-sort-core"], exerciseIds: ["merge-sort-check"] },
  "quicksort-and-partition": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 14, outcomes: ["State a partition invariant", "Relate pivot splits and duplicates to time and stack cost"], traceIds: ["quicksort-and-partition-core"], exerciseIds: ["quicksort-and-partition-check"] },
  "binary-search": { contentVersion: 2, contentReadiness: "ready", estimatedMinutes: 18, outcomes: ["Justify why sorted order lets each comparison discard a range", "Trace present, missing and duplicate values", "Diagnose a non-shrinking interval", "Separate search and insertion costs"], traceIds: ["binary-search-core"], exerciseIds: ["binary-search-prediction", "binary-search-off-by-one", "binary-search-duplicates", "binary-search-insertion-cost", "binary-search-transfer-trace"] },
  "binary-search-on-answer": { contentVersion: 3, contentReadiness: "partial", estimatedMinutes: 18, outcomes: ["State when a feasibility predicate is monotone", "Trace how feasible and infeasible candidates preserve the boundary invariant", "Multiply feasibility-check cost by the number of candidate rates"], traceIds: [], exerciseIds: ["binary-search-answer-monotonicity", "binary-search-answer-boundary-trace"] },
  "queues-and-deque": { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 22, outcomes: ["Distinguish FIFO queues from deques", "Choose an implementation based on which ends change"], traceIds: [], exerciseIds: [] },
  heaps: { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 22, outcomes: ["Maintain a heap's partial-order invariant", "Use a priority queue for repeated minimum/maximum selection"], traceIds: [], exerciseIds: [] },
  "hash-table": { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 22, outcomes: ["Trace hashing, buckets and collisions", "Distinguish expected lookup cost from worst-case cost"], traceIds: [], exerciseIds: [] },
  "hash-chaining": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 12, outcomes: ["Trace entries in collision buckets", "Relate load factor and resizing to expected lookup"], traceIds: ["hash-chaining-core"], exerciseIds: ["hash-chaining-check"] },
  "hash-linear-probing": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 12, outcomes: ["Trace a probe sequence through collisions and tombstones", "Explain clustering and table load effects"], traceIds: [], exerciseIds: [] },
  "binary-search-tree": { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 28, outcomes: ["Trace ordered lookup and tree edits", "Relate tree height and balancing to operation cost"], traceIds: [], exerciseIds: [] },
  "binary-search-tree-operations": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 14, outcomes: ["Trace BST lookup, insertion and deletion", "Find a successor while preserving ordering"], traceIds: ["binary-search-tree-operations-core"], exerciseIds: ["binary-search-tree-operations-check"] },
  "tree-traversals": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 12, outcomes: ["Predict preorder, inorder and postorder sequences", "Trace level-order traversal with a queue"], traceIds: [], exerciseIds: [] },
  "balanced-search-trees": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Explain why balance bounds search-tree height", "Relate local rotations to preserved key order"], traceIds: [], exerciseIds: [] },
  "heap-operations": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 14, outcomes: ["Trace sift-up, sift-down and heap construction", "Derive heapsort's time and extra-space costs"], traceIds: ["heap-operations-core"], exerciseIds: ["heap-operations-check"] },
  "priority-queues": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 12, outcomes: ["Map priority-queue operations to heap operations", "Choose between repeated extraction and sorting once"], traceIds: [], exerciseIds: [] },
  "union-find": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 18, outcomes: ["Track components as sets merge", "Explain path compression and union-by-size"], traceIds: ["union-find-core"], exerciseIds: ["union-find-check"] },
  "sorting-extras": { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 24, outcomes: ["Identify when radix sorting avoids comparison sorting", "Use selection to find order statistics"], traceIds: [], exerciseIds: [] },
  "noncomparison-sorts": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Relate counting-sort cost to key range", "Explain stable digit passes and radix cost"], traceIds: [], exerciseIds: [] },
  "order-statistic-selection": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 12, outcomes: ["Trace quickselect's remaining side", "Compare expected and worst-case work"], traceIds: [], exerciseIds: [] },
  "inversion-counting": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 12, outcomes: ["Define an inversion", "Count cross-run inversions during merge"], traceIds: [], exerciseIds: [] },
  graphs: { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 35, outcomes: ["Choose graph representations", "Trace traversal and shortest-path algorithms", "Compare spanning-tree strategies"], traceIds: [], exerciseIds: [] },
  "graph-representations": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 12, outcomes: ["Compare adjacency-list and matrix space", "Choose representation for graph operations"], traceIds: [], exerciseIds: [] },
  "graph-traversals": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 14, outcomes: ["Trace DFS and BFS discovery", "Explain O(V + E) traversal work"], traceIds: ["graph-traversals-core"], exerciseIds: ["graph-traversals-check"] },
  "topological-order": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 12, outcomes: ["Trace Kahn's algorithm", "Detect when a directed cycle prevents full ordering"], traceIds: [], exerciseIds: [] },
  "shortest-paths": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Choose BFS or Dijkstra from weight assumptions", "Trace edge relaxation and implementation costs"], traceIds: [], exerciseIds: [] },
  "minimum-spanning-trees": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Trace Kruskal's edge choices", "Explain cycle checks and forest behavior"], traceIds: [], exerciseIds: [] },
  "dynamic-programming": { contentVersion: 2, contentReadiness: "partial", estimatedMinutes: 28, outcomes: ["Identify repeated subproblems and state", "Build a bottom-up recurrence", "Analyze time and memory separately"], traceIds: ["dynamic-programming-core"], exerciseIds: ["dynamic-programming-check"] },
  "greedy-algorithms": { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 22, outcomes: ["State a greedy choice", "Use an exchange or cut argument to justify optimality"], traceIds: [], exerciseIds: [] },
  "backtracking-and-array-patterns": { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 30, outcomes: ["Represent choices as a search tree", "Recognize two-pointer, window and prefix-sum patterns"], traceIds: [], exerciseIds: [] },
  "two-pointers": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 12, outcomes: ["State why a pointer may safely move", "Account for total monotone pointer movement"], traceIds: [], exerciseIds: [] },
  "sliding-window": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Maintain a valid contiguous window", "Identify when monotonicity assumptions fail"], traceIds: [], exerciseIds: [] },
  "prefix-sums": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 12, outcomes: ["Derive half-open range sums", "Count target subarrays using prior prefix frequencies"], traceIds: [], exerciseIds: [] },
  "backtracking": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Trace choose, recurse and undo", "Estimate search-tree size and justify pruning"], traceIds: [], exerciseIds: [] },
  "greedy-methods": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["State a greedy decision rule", "Distinguish examples from a correctness proof"], traceIds: [], exerciseIds: [] },
  "dp-state-and-transition": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Define a state and recurrence", "Count state, transition and memory costs"], traceIds: [], exerciseIds: [] },
  strings: { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 30, outcomes: ["Compare text-search and indexing methods", "Choose between tries, hashes and pattern matching"], traceIds: [], exerciseIds: [] },
  "string-search": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Trace KMP fallback after mismatch", "Explain candidate verification in Rabin–Karp"], traceIds: [], exerciseIds: [] },
  "tries-and-text-indexes": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Match text queries to indexes", "Include construction and output costs"], traceIds: [], exerciseIds: [] },
  "range-query-structures": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Compare update and query support", "Choose a range structure for a workload"], traceIds: [], exerciseIds: [] },
  "approximate-membership": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 12, outcomes: ["Distinguish Bloom-filter maybe and absent results", "Relate false positives to memory and probes"], traceIds: [], exerciseIds: [] },
  "storage-engines-and-locality": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 14, outcomes: ["Compare B-tree and LSM work placement", "Explain effects of locality and storage reads"], traceIds: [], exerciseIds: [] },
  "approximation-guarantees": { contentVersion: 1, contentReadiness: "summary", estimatedMinutes: 12, outcomes: ["Prove the constructed set is a vertex cover", "Derive the factor-two approximation guarantee"], traceIds: [], exerciseIds: [] },
  "range-queries-and-approximate-structures": { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 28, outcomes: ["Select a range-query structure for its update/query tradeoff", "Explain false positives and guarantees in approximate structures"], traceIds: [], exerciseIds: [] },
  "storage-and-locality": { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 25, outcomes: ["Relate tree, log and sorted-run structures to storage engines", "Explain why access locality changes practical performance"], traceIds: [], exerciseIds: [] },
  "limits-and-approximation": { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 22, outcomes: ["Separate exact, approximate and assumption-dependent claims", "Interpret a factor-two vertex-cover guarantee"], traceIds: [], exerciseIds: [] },
  "appendix-python-tools": { contentVersion: 1, contentReadiness: "reference", estimatedMinutes: 8, outcomes: ["Look up decorator and directory-walking examples"], traceIds: [], exerciseIds: [] },
};

export const curriculumObjectiveIds: Record<string, string[]> = {
  "analysis-and-library-costs": ["analysis-count-loop-work", "analysis-compare-python-operations"],
  "input-size-and-operation-counts": ["input-size-choose-variable", "input-size-count-loop-work"],
  "asymptotic-growth": ["asymptotic-distinguish-bounds", "asymptotic-compare-growth"],
  "cost-models": ["cost-model-state-assumptions", "cost-model-python-operations"],
  "loop-invariants": ["invariant-state-loop-property", "invariant-check-proof-steps"],
  "arrays-and-python-costs": ["python-sequence-select-structure", "python-sequence-analyze-amortized-cost"],
  "recursion-and-recurrences": ["recursion-identify-shape", "recursion-count-levels-and-stack"],
  "dynamic-array-growth": ["dynamic-array-geometric-growth", "dynamic-array-amortized-append"],
  "singly-linked-list": ["linked-list-trace-links", "linked-list-operation-costs"],
  "list-algorithms": ["list-patterns-slow-fast-split-merge", "list-preserve-pointer-invariants"],
  "fast-slow-pointer-patterns": ["fast-slow-locate-middle-cycle", "fast-slow-preserve-gap"],
  "linked-list-reversal-and-relinking": ["list-reversal-preserve-suffix", "list-relink-boundary-reconnection"],
  "linked-list-merge-and-sort": ["list-merge-head-order", "list-merge-sort-cost"],
  "linked-list-special-cases": ["list-state-preconditions", "list-special-boundary-tests"],
  "stack-basics": ["stack-trace-lifo", "stack-maintain-size-invariant"],
  "monotonic-stack-patterns": ["monotonic-stack-resolve-candidates", "monotonic-stack-count-total-work"],
  "stack-parsing-and-expressions": ["stack-match-nested-delimiters", "stack-trace-operator-precedence"],
  "queue-and-deque-operations": ["queue-trace-fifo", "queue-compare-implementations"],
  "doubly-linked-list-and-lru-cache": ["doubly-linked-maintain-links", "lru-key-and-recency"],
  "doubly-linked-list-operations": ["doubly-linked-update-neighbors", "doubly-linked-known-node-unlink"],
  "lru-cache": ["lru-trace-recency-and-eviction", "lru-analyze-combined-operations"],
  stacks: ["stack-lifo-behavior", "stack-recognize-applications"],
  sorting: ["sorting-compare-costs", "sorting-choose-stability"],
  "comparison-sorts": ["comparison-sort-track-prefix", "comparison-sort-compare-properties"],
  "merge-sort": ["merge-sort-merge-runs", "merge-sort-derive-cost"],
  "quicksort-and-partition": ["quicksort-state-partition", "quicksort-analyze-split-cost"],
  "binary-search": ["binary-search-justify-elimination", "binary-search-trace-boundaries", "binary-search-diagnose-progress", "binary-search-separate-insertion-cost"],
  "binary-search-on-answer": ["binary-search-answer-check-monotonicity", "binary-search-answer-trace-search", "binary-search-answer-multiply-check-cost"],
  "queues-and-deque": ["queue-distinguish-fifo-deque", "queue-choose-ends"],
  heaps: ["heap-maintain-order", "heap-use-priority-queue"],
  "hash-table": ["hash-trace-collisions", "hash-compare-average-worst-case"],
  "hash-chaining": ["hash-chaining-trace-bucket", "hash-chaining-analyze-load-factor"],
  "hash-linear-probing": ["hash-probing-trace-tombstones", "hash-probing-explain-clustering"],
  "binary-search-tree": ["bst-trace-edits", "bst-relate-height-and-cost"],
  "binary-search-tree-operations": ["bst-operations-trace-edits", "bst-operations-find-successor"],
  "tree-traversals": ["tree-traversal-predict-depth-first", "tree-traversal-trace-level-order"],
  "balanced-search-trees": ["balanced-tree-explain-height", "balanced-tree-preserve-order-with-rotations"],
  "heap-operations": ["heap-operations-trace-sift", "heap-operations-derive-heapsort-cost"],
  "priority-queues": ["priority-queue-map-operations", "priority-queue-choose-extraction-or-sort"],
  "union-find": ["union-find-track-components", "union-find-explain-optimizations"],
  "sorting-extras": ["sorting-extras-radix", "sorting-extras-selection"],
  "noncomparison-sorts": ["noncomparison-use-key-range", "noncomparison-derive-radix-cost"],
  "order-statistic-selection": ["selection-trace-quickselect", "selection-compare-cost-risks"],
  "inversion-counting": ["inversion-define-pair", "inversion-count-cross-run"],
  graphs: ["graph-choose-representation", "graph-trace-traversals-paths", "graph-compare-spanning-trees"],
  "graph-representations": ["graph-representation-compare-space", "graph-representation-choose-operations"],
  "graph-traversals": ["graph-traversal-trace-discovery", "graph-traversal-analyze-work"],
  "topological-order": ["topological-order-trace-kahn", "topological-order-detect-cycle"],
  "shortest-paths": ["shortest-path-choose-algorithm", "shortest-path-trace-relaxation"],
  "minimum-spanning-trees": ["mst-trace-kruskal", "mst-explain-cycle-check"],
  "dynamic-programming": ["dp-identify-state", "dp-build-recurrence", "dp-analyze-time-memory"],
  "greedy-algorithms": ["greedy-state-choice", "greedy-justify-choice"],
  "backtracking-and-array-patterns": ["backtracking-represent-choice-tree", "array-recognize-pointer-window-prefix"],
  "two-pointers": ["two-pointers-justify-movement", "two-pointers-count-total-moves"],
  "sliding-window": ["sliding-window-maintain-valid-range", "sliding-window-test-monotonicity"],
  "prefix-sums": ["prefix-sums-derive-range-query", "prefix-sums-count-target-subarrays"],
  "backtracking": ["backtracking-trace-reversible-state", "backtracking-analyze-search-tree"],
  "greedy-methods": ["greedy-methods-state-choice", "greedy-methods-justify-optimality"],
  "dp-state-and-transition": ["dp-state-define-recurrence", "dp-state-analyze-work-memory"],
  strings: ["strings-compare-search-indexing", "strings-choose-data-structure"],
  "string-search": ["string-search-trace-kmp-fallback", "string-search-verify-hash-candidates"],
  "tries-and-text-indexes": ["text-index-match-query", "text-index-include-build-cost"],
  "range-query-structures": ["range-query-compare-operations", "range-query-select-for-workload"],
  "approximate-membership": ["bloom-filter-state-guarantees", "bloom-filter-explain-false-positive"],
  "storage-engines-and-locality": ["storage-compare-write-read-tradeoffs", "storage-engines-explain-locality"],
  "approximation-guarantees": ["approximation-prove-feasibility", "approximation-derive-ratio"],
  "range-queries-and-approximate-structures": ["range-query-choose-update-tradeoff", "approximate-interpret-guarantees"],
  "storage-and-locality": ["storage-relate-engine-structures", "storage-explain-locality"],
  "limits-and-approximation": ["limits-separate-guarantees", "approximation-interpret-factor-two"],
  "appendix-python-tools": ["python-tools-look-up-examples"],
};
